### ISSUE TITLE
README gives reference to an incorrect account encoding spec

### ISSUE THREAD

**Issue by timohanke** [dfinity/ic-js#382]
https://github.com/dfinity/ic-js/blob/4eb189722c6e4052edef3ecd98e23d6330240e0b/packages/ledger/README.md?plain=1#L66

The reference given in that line is outdated and incorrect.

The correct link is: https://github.com/dfinity/ICRC-1/blob/main/standards/ICRC-1/TextualEncoding.md

**Comment by peterpeterparker** [comment]
Thanks. READMEs are automatically generated be the comments in code. Therefore this will be automatically resolved when  #381 will be resolved.
