### ISSUE TITLE
AccountIdentifier error

### ISSUE THREAD

**Issue by honopu** [dfinity/ic-js#409]
When i try to use AccountIdentifier.fromPrincipal
<img width="812" alt="image" src="https://github.com/dfinity/ic-js/assets/85238703/9ff0a988-2f57-48d8-9c91-ef6c18fe6b98">

Error in browser
<img width="879" alt="image" src="https://github.com/dfinity/ic-js/assets/85238703/e5c48a7b-88c8-44f1-a33b-d96b5cf0561d">

This is the packages version
<img width="543" alt="image" src="https://github.com/dfinity/ic-js/assets/85238703/fca01ac2-c62a-4efd-a107-2e06b05a158b">

**Comment by peterpeterparker** [comment]
The issue is one your side given the fact that `AccountIdentifier. fromPrincipal` is covered by a test https://github.com/dfinity/ic-js/blob/8ec4222fd954a536aaea8c92c5cb282864d951f6/packages/nns/src/account_identifier.spec.ts#L85 and also used in NNS dapp.

Is your app open source?

**Comment by honopu** [comment]
> The issue is one your side given the fact that `AccountIdentifier. fromPrincipal` is covered by a [test](https://github.com/dfinity/ic-js/blob/8ec4222fd954a536aaea8c92c5cb282864d951f6/packages/nns/src/account_identifier.spec.ts#L85) and also used in NNS dapp.
> 
> Is your app open source?

You can use this demo
https://github.com/honopu/account_identifier

**Comment by honopu** [comment]
> The issue is one your side given the fact that `AccountIdentifier. fromPrincipal` is covered by a [test](https://github.com/dfinity/ic-js/blob/8ec4222fd954a536aaea8c92c5cb282864d951f6/packages/nns/src/account_identifier.spec.ts#L85) and also used in NNS dapp.
> 
> Is your app open source?

Thanks for your answer. Problem solved

**Comment by peterpeterparker** [comment]
Great to hear! What was the issue?
