### ISSUE TITLE
TypeError: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by bobekas** [dfinity/ic-js#462]
`TypeError: Right side of assignment cannot be destructured`
I'm trying to call IcrcLedgerCanister.metadata()... 
Any suggestions?

**Comment by peterpeterparker** [comment]
Based only on your short message is a bit hard to tell, can you share the all code or a link to the code?

**Comment by peterpeterparker** [comment]
Given the fact that you asked the same question on [Discord](https://discord.com/channels/748416164832608337/1173494846791626813/1173494846791626813) and since it seems that it's more a support question than a possible bug, let's continue there.
