### ISSUE TITLE
Generate complete TypeScript did.d.ts/idl.d.ts declaration files

### ISSUE THREAD

**Issue by ByronBecker** [dfinity/ic-js#761]
Currently, this is empty

https://github.com/dfinity/ic-js/blob/main/packages/ic-management/candid/ic-management.idl.d.ts

The entire file 👇 
```
import type { IDL } from "@dfinity/candid";
export const idlFactory: IDL.InterfaceFactory;
```

We have a few scripts that generate declarations and then replace various contents of the did.d.js file and convert it into a did.d.ts file, for our project,

For example

```
          contents = contents.replace(
            "export const idlFactory = ({ IDL }) => {",
            'import { IDL } from "@dfinity/candid";\nexport const idlFactory : IDL.InterfaceFactory = ({ IDL }) => {'
          );
          contents = contents.replace(
            "export const init = ({ IDL }) => { return []; };",
            "export const init = (context: { IDL: typeof IDL }) => { return [] as IDL.Type[]; };"
          );
```

but since this is a library it would be nice if the library already contained these typed declarations.

**Comment by peterpeterparker** [comment]
The declarations are generated and shipped with the library. You picked the wrong file.

👉 https://github.com/dfinity/ic-js/blob/main/packages/ic-management/candid/ic-management.d.ts

**Comment by ByronBecker** [comment]
@peterpeterparker right, but the idl typescript bindings aren't there.

**Comment by peterpeterparker** [comment]
Not sure what's IDL Type script. [didc](https://github.com/dfinity/candid/tree/master/tools/didc) generates ts and js. 
Those are generated in s://github.com/dfinity/ic-js/blob/main/packages/ic-management/candid.
i.e. there isn't any other file that can be generated to my knowledge.

**Comment by peterpeterparker** [comment]
Note that we also generate the file with different idl files and a common ts file because the library support both queries and updates calls.

**Comment by ByronBecker** [comment]
> Not sure what's IDL Type script. [didc](https://github.com/dfinity/candid/tree/master/tools/didc) generates ts and js. 
> 

The interface factory that's required in agent-js when creating an actor

https://agent-js.icp.xyz/agent/classes/Actor.html#createActor

**Comment by ByronBecker** [comment]
We manipulate this on our end in our repositories, but wish that didc did this for us.

I guess it's an adjacent issue not directly related to ic-js

**Comment by peterpeterparker** [comment]
> The interface factory that's required in agent-js when creating an actor

Service import: https://github.com/dfinity/ic-js/blob/31fbfce550e17aa61d958b63068305cf8ed5e4ae/packages/ic-management/src/ic-management.canister.ts#L10

i.e. https://github.com/dfinity/ic-js/blob/main/packages/ic-management/candid/ic-management.d.ts

**Comment by peterpeterparker** [comment]
Actually, I'm wondering, why are you looking to access the candid types that are generated for the need of the library instead of using the library? Any functions missing?

**Comment by ByronBecker** [comment]
Got it! I misspoke, was referring to the idl factory all along. Makes sense now
